{"HISTORY":"","SYNTAX":"<!-- --><br>GetException(<i xmlns:fn=\"http:\/\/www.w3.org\/2005\/xpath-functions\" xmlns:fo=\"http:\/\/www.w3.org\/1999\/XSL\/Format\" xmlns:xs=\"http:\/\/www.w3.org\/2001\/XMLSchema\">object<\/i>)<br>","CATEGORY":"System functions","PAGENAME":"GetException","SEEALSO":"","DESCRIPTION":"Used with the cftry and cfcatch tags. Retrieves a Java exception object from a Java object.","LICENCE":"http:\/\/help.adobe.com\/en_US\/ColdFusion\/10.0\/LegalNotices\/index.html","EXAMPLE":"<!-- --><br>&lt;!--- Create the Java object reference ---&gt; \r\n&lt;cfobject action = create type = java class = primativetype name = myObj&gt; \r\n&lt;!--- Calls the object's constructor ---&gt; \r\n&lt;cfset void = myObj.init()&gt; \r\n&lt;cftry&gt; \r\n&lt;cfset void = myObj.DoException() &gt; \r\n&lt;Cfcatch type = &quot;Any&quot;&gt; \r\n    &lt;cfset exception = GetException(myObj)&gt; \r\n&lt;!--- User can call any valid method on the exception object.---&gt; \r\n    &lt;cfset message = exception.toString()&gt; \r\n    &lt;cfoutput&gt; \r\n        Error&lt;br&gt; \r\n        I got exception &lt;br&gt; \r\n        &lt;br&gt; The exception message is: #message# &lt;br&gt; \r\n    &lt;\/cfoutput&gt;  \r\n&lt;\/cfcatch&gt; \r\n&lt;\/cftry&gt;<br>","USAGE":"<!-- --><br>ColdFusion stores a Java exception object for each method call on a Java object. Subsequent method calls reset the exception object. To get the current exception object, call <samp class=\"codeph\">GetException<\/samp> on the Java object before other methods are invoked on it.<br>","Parameter":[{"DESCRIPTION":"A Java object.","Parameter":"object"}]}